name: Gentle_Student
description: An application that makes students engage more in their community.

dependencies:
  flutter:
    sdk: flutter

  dynamic_theme:
    git:
      url: git://github.com/Norbert515/dynamic_theme.git

  cupertino_icons: any

  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  firebase_storage: any

  image_picker: any
  local_notifications: any
  flutter_local_notifications: any
  beacons: any
  flutter_map: any
  date_format: any
  flutter_html_view: any
  intro_views_flutter: any
  cached_network_image: any
  url_launcher: any
  sqflite: any
  mailer2: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: any

flutter_icons:
  android: true 
  ios: "Gentlestudent"
  image_path: "assets/icon/app_logo.png"
  image_path_android: "assets/icon/app_logo.png"
  image_path_ios: "assets/icon/app_logo.png"
  adaptive_icon_background: "#FFFAFAFA"
  adaptive_icon_foreground: "assets/icon/app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_logo.png
    - assets/icon/logo.png
    - assets/tutorial/beacon.png
    - assets/tutorial/bluetooth.png
    - assets/tutorial/challenge.png
  fonts:
      - family: NeoSansPro
        fonts:
          - asset: assets/NeoSansPro-Regular.otf